/**
 * Cinematic rig backgrounds. These files live in public/backgrounds/ and are
 * generated by scripts/generate-rig-backgrounds.py. To use your own imagery,
 * drop photos into that folder and list their paths here.
 */
export const RIG_BACKGROUNDS: string[] = [
  "/backgrounds/rig-01.jpg",
  "/backgrounds/rig-02.jpg",
  "/backgrounds/rig-03.jpg",
  "/backgrounds/rig-04.jpg",
  "/backgrounds/rig-05.jpg",
  "/backgrounds/rig-06.jpg",
  "/backgrounds/rig-07.jpg",
  "/backgrounds/rig-08.jpg",
  "/backgrounds/rig-09.jpg",
  "/backgrounds/rig-10.jpg",
];

/**
 * Assign a background to each company name. Shuffled so the order feels random,
 * but stable for the lifetime of the call (no jarring re-randomizing mid-show),
 * and never repeats a background until the pool is exhausted.
 */
export function assignBackgrounds(companies: string[]): Record<string, string> {
  const pool = [...RIG_BACKGROUNDS];
  // Fisher–Yates shuffle.
  for (let i = pool.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [pool[i], pool[j]] = [pool[j], pool[i]];
  }

  const map: Record<string, string> = {};
  companies.forEach((company, i) => {
    map[company] = pool[i % pool.length];
  });
  return map;
}
